# Curated list of ~100 well-documented players who are 35+ years old as of
# today and were top-level players at some point over the past two decades
# (2004-2024). Names are resolved to Transfermarkt player IDs at scrape time
# via the search endpoint and cached in the database, so this list only ever
# needs to contain human-readable names.
#
# A handful of names are ambiguous on Transfermarkt (common names, multiple
# pro players sharing them). MANUAL_TM_ID_OVERRIDES lets you pin the correct
# Transfermarkt player ID for those after checking the first scrape's
# resolution log (see `scrape --show-resolutions`).

PLAYER_NAMES = [
    "Lionel Messi",
    "Cristiano Ronaldo",
    "Luka Modric",
    "Karim Benzema",
    "Sergio Ramos",
    "Toni Kroos",
    "Thiago Silva",
    "Robert Lewandowski",
    "Luis Suarez",
    "Angel Di Maria",
    "Gonzalo Higuain",
    "Marcelo",
    "Dani Alves",
    "Gianluigi Buffon",
    "Iker Casillas",
    "Andres Iniesta",
    "Xavi Hernandez",
    "Andrea Pirlo",
    "Gerard Pique",
    "Sergio Busquets",
    "Cesc Fabregas",
    "David Silva",
    "Mesut Ozil",
    "Zlatan Ibrahimovic",
    "Wayne Rooney",
    "Steven Gerrard",
    "Frank Lampard",
    "Didier Drogba",
    "Yaya Toure",
    "Kolo Toure",
    "John Terry",
    "Ashley Cole",
    "Petr Cech",
    "Edinson Cavani",
    "Radamel Falcao",
    "Diego Godin",
    "Javier Mascherano",
    "Claudio Bravo",
    "Arturo Vidal",
    "Alexis Sanchez",
    "Miralem Pjanic",
    "Marek Hamsik",
    "Gareth Bale",
    "James Rodriguez",
    "Antoine Griezmann",
    "N'Golo Kante",
    "Hugo Lloris",
    "Olivier Giroud",
    "Blaise Matuidi",
    "Mario Mandzukic",
    "Ivan Rakitic",
    "Ivan Perisic",
    "Robert Pires",
    "Thierry Henry",
    "Ryan Giggs",
    "Paul Scholes",
    "Rio Ferdinand",
    "Nemanja Vidic",
    "Patrice Evra",
    "Michael Carrick",
    "Wesley Sneijder",
    "Robin van Persie",
    "Arjen Robben",
    "Franck Ribery",
    "Philipp Lahm",
    "Bastian Schweinsteiger",
    "Manuel Neuer",
    "Thomas Muller",
    "Mats Hummels",
    "Jerome Boateng",
    "Miroslav Klose",
    "Lukas Podolski",
    "Marco Reus",
    "Edin Dzeko",
    "Samir Nasri",
    "David de Gea",
    "Vincent Kompany",
    "David Luiz",
    "Diego Forlan",
    "Kaka",
    "Ronaldinho",
    "Fabio Cannavaro",
    "Alessandro Nesta",
    "Andrea Barzagli",
    "Giorgio Chiellini",
    "Leonardo Bonucci",
    "Francesco Totti",
    "Daniele De Rossi",
    "Claudio Marchisio",
    "Antonio Di Natale",
    "Samuel Eto'o",
    "Diego Milito",
    "Javier Zanetti",
    "Esteban Cambiasso",
    "Walter Samuel",
    "Cristian Chivu",
    "Giuseppe Rossi",
    "Alberto Gilardino",
    "Fernando Torres",
    "David Villa",
]

assert len(PLAYER_NAMES) == len(set(PLAYER_NAMES)), "duplicate player name in PLAYER_NAMES"

# name -> Transfermarkt player id (string), for names that resolve incorrectly
# via plain-text search (e.g. very common names).
MANUAL_TM_ID_OVERRIDES: dict[str, str] = {}
